name: Playwright Tests

on:
  push:
    branches: [ main, master ]  # Trigger on push to main or master branches
  pull_request:
    branches: [ main, master ]  # Trigger on pull requests to main or master branches

jobs:
  test:
    timeout-minutes: 60  # Set a timeout for the job to prevent hanging
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v4  # Check out the repository code
    - uses: actions/setup-node@v4  # Set up Node.js environment
      with:
        node-version: lts/*  # Use the latest LTS version of Node.js

    - name: Install dependencies
      run: npm ci  # Install project dependencies using npm

    - name: Install Playwright Browsers
      # Install only the Chromium browser to save time and resources
      run: npx playwright install chromium

    - name: Run Playwright tests
      # Run tests only in the Chromium browser and execute a specific test file
      run: npx playwright test tests/example.spec.ts --project=chromium

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}  
      # Upload artifacts only if the job is not cancelled
      with:
        name: playwright-report  # Name of the artifact
        path: playwright-report/  # Path to the report directory
        retention-days: 30  # Retain the artifact for 30 days